services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_DB=abadatabase
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=secret
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: abadatabase
      DB_USERNAME: myuser
      DB_PASSWORD: secret

  frontend:
    build:
      context: https://github.com/witermendonca/FATEC_aba_project.git#feature/aula-computacao-nuvem-2
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    depends_on:
      - backend

volumes:
  postgres_data:
